<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>new</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-10-17T17:47:44</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>456f6bdf-48a6-4b44-83ed-4ed649b519cb</testSuiteGuid>
   <testCaseLink>
      <guid>3d031bd4-9098-40b4-b99d-ea38596ad14b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Common/EsbToken</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>ed423a49-84ec-4a86-9d3f-18e125ca61d9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Library/Community/New Test Case of jira</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>823196e4-3e12-4707-bbb8-d545d583cccf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10be682c-bc1a-49a3-966b-33bff77af7b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8a94a86-f2d1-422d-88bb-c10203b93bc2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>553ea4a0-9b08-494c-96a4-e70dcc2aee36</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a8e2aad-f5cc-44fe-b9a3-95566f156397</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96c811d9-e252-4a59-822d-5de3f9a1c77c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc872f62-e40a-4b4a-ac33-c4adc16305a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f461cbb5-1366-4b60-b5a0-8f5d309229d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95354b08-fbc1-46fc-a3a9-2de0ccf1f046</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ccc1d7cd-35c4-4bf9-b529-3c07e36ba9e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16264ab7-cf25-45a2-b437-a0d34f7aef54</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5983f6f3-23e8-449b-8b93-17ecb49603f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6866748a-540d-4252-a656-cf8b4999da78</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f06c5e5c-4410-47de-956c-ce2c159b700d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestCases/Community/new</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
